### PR TITLE
Add counters to index.html

### PR DESCRIPTION
**Pull request by castos**
Add Yandex.Metrika counter code and Google Analytics tracking code to the index page

### CODE REVIEW

**Comment by ed-asriyan** [comment]
We already have an analytics in [/app/analytics.js](https://github.com/BMSTU-Schedule/web/blob/master/app/analytics.js). This file also contains an API for tracking custom events.

**Comment by castos** [comment]
What about Yandex?

**Comment by castos** [comment]
Also gtag.js is the next generation of tracking from Google. You are using analytics.js from Google, I see.

**Comment by ed-asriyan** [comment]
Adding Yandex is a good idea to move the site higher in search results. Can you insert `52426366` as Yandex counter ID and remove gtag.js? After that I will merge your PR.
Migration to gtag is a sensible idea, but it may break events statistics. It should be done in the future.

Thanks for PR :)

**Comment by castos** [comment]
Done.
Thanks for useful project!

**Pull request merged**
